# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: 2026 Roland Nagtegaal <perpetualbits@gmail.com>
# """
# CE substrate reference model — core (Phase 2).
# 
# Models, per ce-ecid-substrate / ce-axioms:
#   - one per-hart ECID array of fixed-width records {ecs, owner, vnum}
#     (slot = index; free iff ecs is None)                              [S-2, S-3, S-4]
#   - the hart-local FORWARD INDEX of the *running* context only:
#     a dense-with-holes vnum->slot list, built by the ownership
#     instructions, regenerated on switch-in, NEVER written to memory   [S-10]
#   - banks + per-slot BANK BINDING giving O(1) slot->bank lookup;
#     software never names a bank                                       [S-11, S-14]
#   - instructions: ec_ir, ec_it, ec_ot, ec_ob, bk_ie, contains         [O-5..O-9]
#   - an invariant checker run after every operation
# 
# BEHAVIOURAL model of the substrate's logic and invariants. NOT a RISC-V
# hart: it does not execute guest instructions, model cycles, or prove RTL.
# 
# Design note on the forward index (the point the author was firm about):
# it is a hart-local cache of the CURRENT context's children only. It is
# held here as `self.fwd` (one running context) — NOT a standing
# [owner][vnum] table in memory. On a switch it is regenerated by scanning
# the array (slow path, fine). No slot number is ever persisted to RAM.
# The dense-with-holes shape (a torn-down child leaves INVALID; survivors
# keep their vnums) is modelled by the regeneration preserving vnums.
# """

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional


class CEError(Exception):
    """An illegal operation: a trap, in hardware terms. Software's fault."""


class InvariantError(Exception):
    """The structure is in an impossible state: a bug in MODEL or DESIGN,
    never something software should be able to cause."""


ROOT = 0
INVALID = None  # a hole in the dense-with-holes forward index


@dataclass
class Record:
    """One ECID array record. slot is the index, not stored."""
    ecs: Optional[int] = None   # ECS pointer; None => free slot
    owner: int = ROOT           # up-pointer to parent slot
    vnum: int = 0               # number in owner's universe (0 = self)


@dataclass
class Bank:
    """Register-file-sized SRAM holding one context's state. Carries an
    owner up-pointer (the truth, for checking). Software never names it."""
    owner: Optional[int] = None     # ECID slot that owns this bank, or None=free
    kind: str = "scalar"            # "scalar" or "vmt"
    state: Optional[str] = None     # placeholder for saved register state


class Hart:
    def __init__(self, hart_id: int, n_slots: int,
                 n_scalar_banks: int = 8, n_vmt_banks: int = 4):
        self.hart_id = hart_id
        self.n_slots = n_slots
        self.array: list[Record] = [Record() for _ in range(n_slots)]

        # Bank pool + per-slot binding (CE-private; software never sees these).
        self.banks: list[Bank] = (
            [Bank(kind="scalar") for _ in range(n_scalar_banks)] +
            [Bank(kind="vmt") for _ in range(n_vmt_banks)]
        )
        # BankBinding[slot] = {"scalar": bank_id|None, "vmt": bank_id|None}
        self.binding: list[dict] = [
            {"scalar": None, "vmt": None} for _ in range(n_slots)
        ]

        # Root exists from boot, owns itself, and (own-bank rule, S-12) holds
        # a scalar bank for itself if one is available.
        self.array[ROOT] = Record(ecs=_ecs_for(ROOT), owner=ROOT, vnum=0)
        self._give_bank(ROOT, "scalar")

        self.current: int = ROOT
        # Forward index of the CURRENT context. Dense-with-holes: index by
        # vnum (1..max), value = slot or INVALID. Hart-local, never in RAM.
        self.fwd: list = []
        self._rebuild_fwd()
        self.check()

    # ---- helpers -------------------------------------------------------

    def _free_slot(self) -> int:
        for s in range(self.n_slots):
            if self.array[s].ecs is None:
                return s
        raise CEError("ECID array exhausted: no free slot")

    def _free_bank(self, kind: str) -> int:
        for i, b in enumerate(self.banks):
            if b.kind == kind and b.owner is None:
                return i
        raise CEError(f"no free {kind} bank")

    def _give_bank(self, slot: int, kind: str) -> Optional[int]:
        """Bind a free bank of `kind` to `slot`. Returns bank id, or None if
        none free (root at boot tolerates absence in tiny configs)."""
        try:
            bid = self._free_bank(kind)
        except CEError:
            return None
        self.banks[bid].owner = slot
        self.binding[slot][kind] = bid
        return bid

    def _children(self, parent: int) -> list[int]:
        """Slots whose owner == parent (excluding self). Slow-path scan."""
        return [s for s in range(self.n_slots)
                if s != parent
                and self.array[s].ecs is not None
                and self.array[s].owner == parent]

    def _rebuild_fwd(self) -> None:
        """Regenerate the running context's dense-with-holes forward index
        from the array (S-10: regenerated on entry, not loaded from memory)."""
        cur = self.current
        kids = self._children(cur)
        if not kids:
            self.fwd = []
            return
        maxv = max(self.array[s].vnum for s in kids)
        f = [INVALID] * (maxv + 1)   # index 0 unused (vnum 0 = self)
        for s in kids:
            f[self.array[s].vnum] = s
        self.fwd = f

    def _fwd_get(self, vnum: int):
        """Resolve a vnum via the forward index, or None if hole / out of range."""
        if vnum <= 0 or vnum >= len(self.fwd):
            return None
        return self.fwd[vnum]

    def _next_vnum(self, parent: int) -> int:
        """Lowest unused vnum >= 1. Gaps from teardown are reusable; existing
        survivors are never renumbered (S-7)."""
        used = {self.array[s].vnum for s in self._children(parent)}
        v = 1
        while v in used:
            v += 1
        return v

    def _is_descendant(self, x: int, ancestor: int) -> bool:
        seen, cur = 0, x
        while True:
            if cur == ancestor:
                return True
            if cur == ROOT:
                return False
            cur = self.array[cur].owner
            seen += 1
            if seen > self.n_slots:
                raise InvariantError("ownership chain does not terminate at root")

    # ---- ownership instructions ---------------------------------------

    def ec_ir(self, parent: Optional[int] = None) -> int:
        """Allocate a new ECID as a child of `parent` (default: running ctx).
        Returns the child's VNUM only (software never sees the slot)."""
        if parent is None:
            parent = self.current
        if self.array[parent].ecs is None:
            raise CEError(f"parent slot {parent} is not a live ECID")
        slot = self._free_slot()
        vnum = self._next_vnum(parent)
        self.array[slot] = Record(ecs=_ecs_for(slot), owner=parent, vnum=vnum)
        if parent == self.current:
            self._rebuild_fwd()   # entry enters the running parent's live index
        self.check()
        return vnum

    def ec_it(self, tenant_vnum: int, count: int) -> None:
        """Delegate `count` UNUSED ECIDs to a tenant the running ctx owns
        (O-6: only unused ECIDs, never a populated subtree)."""
        if self._fwd_get(tenant_vnum) is None:
            raise CEError(f"vnum {tenant_vnum} is not a child of the running context")
        tenant = self._fwd_get(tenant_vnum)
        for _ in range(count):
            slot = self._free_slot()
            vnum = self._next_vnum(tenant)
            self.array[slot] = Record(ecs=_ecs_for(slot), owner=tenant, vnum=vnum)
            # belong to the tenant, not to us: do NOT enter our fwd
        self.check()

    def ec_ot(self, tenant_vnum: int) -> int:
        """Tear down a child (by vnum) and its whole subtree. Always succeeds.
        Returns count of ECIDs freed. Frees banks; survivors keep vnums."""
        if self._fwd_get(tenant_vnum) is None:
            raise CEError(f"vnum {tenant_vnum} is not a child of the running context")
        tenant = self._fwd_get(tenant_vnum)
        freed = self._teardown(tenant)
        self._rebuild_fwd()   # the gap becomes a hole; survivors unchanged
        self.check()
        return freed

    def _teardown(self, slot: int) -> int:
        freed = 0
        for child in self._children(slot):
            freed += self._teardown(child)
        # reclaim banks (only-on-teardown path, O-7) and scrub (O-8)
        for kind in ("scalar", "vmt"):
            bid = self.binding[slot][kind]
            if bid is not None:
                self.banks[bid] = Bank(kind=kind)  # zeroed, owner=None
            self.binding[slot][kind] = None
        self.array[slot] = Record()  # ecs=None => free
        return freed + 1

    # ---- banks ---------------------------------------------------------

    def bk_ie(self, child_vnum: int, kind: str = "scalar") -> None:
        """Give a free bank of `kind` to a child (by vnum) of the running ctx.
        Software names neither the bank nor the slot (S-11)."""
        child = self._fwd_get(child_vnum)
        if child is None:
            raise CEError(f"vnum {child_vnum} is not a child of the running context")
        if self.binding[child][kind] is not None:
            raise CEError(f"child vnum {child_vnum} already has a {kind} bank")
        if self._give_bank(child, kind) is None:
            raise CEError(f"no free {kind} bank")
        self.check()

    # ---- switching -----------------------------------------------------

    def ec_ob(self, child_vnum: int) -> None:
        """Fast-path switch into a child by vnum. The four steps from the
        diagram: resolve via forward index, check the truth, find+check the
        bank, become current. Must not scan (besides the forward-index read)."""
        if child_vnum == 0:
            raise CEError("cannot switch to self (vnum 0) via a child switch")
        target = self._fwd_get(child_vnum)               # 1. forward index
        if target is None:
            raise CEError(f"vnum {child_vnum} is not a child of the running context")
        r = self.array[target]                           # 2. check the truth
        if r.owner != self.current or r.vnum != child_vnum:
            raise InvariantError("forward index disagrees with the array")
        bid = self.binding[target]["scalar"]             # 3. find the bank
        if bid is None:
            raise CEError(f"target vnum {child_vnum} has no scalar bank to restore")
        if self.banks[bid].owner != target:
            raise InvariantError("bank binding disagrees with bank owner")
        self.current = target                            # 4. switch
        self._rebuild_fwd()
        self.check()

    def switch_to_parent(self) -> None:
        """Return to the owner of the running context (models going back up to
        a scheduler). Root's parent is itself."""
        self.current = self.array[self.current].owner
        self._rebuild_fwd()
        self.check()

    # ---- invariant checker ---------------------------------------------

    def check(self) -> None:
        a = self.array
        if a[ROOT].owner != ROOT or a[ROOT].vnum != 0 or a[ROOT].ecs is None:
            raise InvariantError("root invariant violated")
        for s in range(self.n_slots):
            r = a[s]
            if r.ecs is None:
                # free slot must hold no bank binding
                if self.binding[s]["scalar"] is not None or self.binding[s]["vmt"] is not None:
                    raise InvariantError(f"free slot {s} still has a bank binding")
                continue
            if a[r.owner].ecs is None:
                raise InvariantError(f"slot {s}: owner {r.owner} is free")
            if not self._is_descendant(s, ROOT):
                raise InvariantError(f"slot {s}: ownership does not reach root")
            if r.owner == s and s != ROOT:
                raise InvariantError(f"slot {s}: self-owning non-root")
        # vnum uniqueness among siblings; 0 only for self
        for parent in range(self.n_slots):
            if a[parent].ecs is None:
                continue
            seen = {}
            for c in self._children(parent):
                v = a[c].vnum
                if v == 0:
                    raise InvariantError(f"child {c} of {parent} has vnum 0")
                if v in seen:
                    raise InvariantError(f"vnum {v} duplicated under {parent}")
                seen[v] = c
        # bank bindings agree with bank owners, both directions
        for s in range(self.n_slots):
            for kind in ("scalar", "vmt"):
                bid = self.binding[s][kind]
                if bid is not None:
                    if self.banks[bid].owner != s:
                        raise InvariantError(f"binding {s}.{kind}->{bid} but bank owner={self.banks[bid].owner}")
                    if self.banks[bid].kind != kind:
                        raise InvariantError(f"binding {s}.{kind}->{bid} but bank kind={self.banks[bid].kind}")
        for i, b in enumerate(self.banks):
            if b.owner is not None:
                if self.array[b.owner].ecs is None:
                    raise InvariantError(f"bank {i} owned by free slot {b.owner}")
                if self.binding[b.owner][b.kind] != i:
                    raise InvariantError(f"bank {i} owner {b.owner} has no back-binding")
        # forward index matches the array exactly, and is dense-with-holes
        cur = self.current
        kids = self._children(cur)
        expect = {self.array[s].vnum: s for s in kids}
        got = {v: s for v, s in enumerate(self.fwd) if s is not INVALID}
        if got != expect:
            raise InvariantError(f"forward index out of sync for current {cur}: "
                                 f"got={got} expected={expect}")

    # ---- inspection ----------------------------------------------------

    def snapshot(self) -> str:
        lines = []
        for s in range(self.n_slots):
            r = self.array[s]
            if r.ecs is not None:
                b = self.binding[s]
                bank = ""
                if b["scalar"] is not None or b["vmt"] is not None:
                    parts = []
                    if b["scalar"] is not None:
                        parts.append(f"scalar#{b['scalar']}")
                    if b["vmt"] is not None:
                        parts.append(f"vmt#{b['vmt']}")
                    bank = "  bank=" + ",".join(parts)
                tag = "  <= current" if s == self.current else ""
                lines.append(f"  slot {s}: owner={r.owner} vnum={r.vnum}{bank}{tag}")
        # dense-with-holes view of the forward index
        cells = []
        for v, s in enumerate(self.fwd):
            if v == 0:
                continue
            cells.append(f"{v}->{s if s is not INVALID else 'INVALID'}")
        lines.append(f"  current={self.current}  fwd=[{', '.join(cells)}]")
        return "\n".join(lines)


def _ecs_for(slot: int) -> int:
    return 0x1000 + slot
